### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by Llewellynvdm** [sermonindex/audio_api#3]
https://github.com/sermonindex/api/blob/04f7c8cb793035e4c718dca7cba676e4502d656d/topic/abandonment.json#L4

At this time we use `audio_sermons` but I was thinking to amalgamate the videos into this same API. Which would mean a new section called `video_sermons` and that could complicate things for us.

So I was wondering what about changing `audio_sermons` to just `sermons` or `media` and then within each sermon, we add a little field called `type` where we do the separation.

@sermonindex-dev or do you prefer they be completely separated? Maybe not even in the same API?

**Comment by sermonindex-dev** [comment]
there could be an issue with duplicate or similar titles perhaps?   I think it is doable. 

It could be more clear to have the videos separate as there are no scripture references or topics for the videos.

If we add  the text sermons to the Api in the future also there are no topics or scripture references to them either.  I have thought about trying to scrap the text sermons for scripture references and the first 2 references show as the scriptures for that text sermon, I am sure there is a script written that could do this easily.

Maybe use.  video_sermons.   text_sermons.       it might make it more clear and some people might want to just use the audio sermons as that is the most popular and most functions with it.   It could get confusing for people to combine them all together.  Just my thought.

**Comment by Llewellynvdm** [comment]
Okay but then I would say, lets call this repo, instead of `api`, `audio_api`, and then the other `text_api`, and `video_api`. That way they are clearly separate and not even in the same file or project. Allowing each to have its own conventions and approach.

We then also change the `audio_sermons` field name to `sermons` and keep that as a convention in the other.

We should make these changes now in the beginning since once the word gets out it will be come hard to change things without breaking other things build on-top if these API's.

**Comment by sermonindex-dev** [comment]
sounds great, that is logical and makes sense.
