### ISSUE TITLE
Topics that have the same names

### ISSUE THREAD

**Issue by Llewellynvdm** [sermonindex/audio_api#5]
Brother @sermonindex-dev  can you take a look at this list https://github.com/sermonindex/audio_api/blob/master/topic/_sermonindex.json

You will see there are a few topics that have names that are very close to each other, could we merge them as well, and can you point out which to keep?

**Comment by Llewellynvdm** [comment]
Like

```
    "audio_book": "\/topic\/audio_book.json",
    "audio_books": "\/topic\/audio_books.json",
```
We could keep just `audio_books`

This one is more tricky, so we need your input
```
    "anabaptism": "\/topic\/anabaptism.json",
    "anabaptist": "\/topic\/anabaptist.json",
    "anabaptist_history": "\/topic\/anabaptist_history.json",
```
We could just combine them into `anabaptist` is what I think... but it up to you, so if you can ask someone else to do it, or if you can I will be very happy to apply the changes.

**Comment by sermonindex-dev** [comment]
Also we could do.    `godly_music`

there are over 1000 mp3 music files that could be separated this way?

For the topics lets keep them "as-is"  as I believe some will search for different terms and it could just help to leave them as they are. 

It would take much time to re-sort all of them on the database. I think its fairly useable as-is.

**Comment by Llewellynvdm** [comment]
I closed it because it is up to you... but just that you know the query to change on looks like this:
```sql
UPDATE `mydownloads_downloads`
SET `topic` = 'babylon'
WHERE `topic` = 'bablyon'
```
And
```sql
UPDATE `mydownloads_downloads`
SET `topic` = 'backsliding'
WHERE `topic` = 'backslidding'
```
And
```sql
UPDATE `mydownloads_downloads`
SET `topic` = 'behaviour'
WHERE `topic` = 'behaviors'
```
And
```sql
UPDATE `mydownloads_downloads`
SET `topic` = 'bondages'
WHERE `topic` = 'bondage'
```
You do have over 2000+ topics and combining the obvious duplicates or misspelled once would help. But okay... fine with me it is all automated anyway, I mean all script who use this API start with the _sermonindex.json file in each folder and so they get the list that match the content.

**Comment by sermonindex-dev** [comment]
Yes I think for now we keep the topics as-is. as some will search for plural names and not plural, etc some searches that use the api will not be able to be smart enough to find either. So I think it works for now, in the future I could work on cleaning up the topics.
