### ISSUE TITLE
Improvement to API

### ISSUE THREAD

**Issue by Llewellynvdm** [sermonindex/audio_api#6]
The only major change is that I removed some of the speaker details from each sermon object, and also changed the key name to access the speaker from preacher_name to speaker_name.

Then added areas are speaker_sermons and topic_sermons which is basically the fist steps towards the new implementation. Also added a new file with all the speaker details in the root folder.

@sermonindex-dev @sherebiahtishbi Please share any more thoughts and ideas to continue the improvement that we have started.

**Comment by sermonindex-dev** [comment]
thanks brother, this should lessen the call load, I have been testing the software (which is now live on GitHub) and things are well so far. Thanks for implimenting this. I will wait for Sherebiah to chime in.

**Comment by sherebiahtishbi** [comment]
Brother I have made minor updates to About popup. Have updated the
installer....pls check and let me know.

Unfortunately due to competing priorities I was not able to create the
windows installer but Mac and Linux installers are upto date .

Not sure if new API change coming in but late have any impact on the app.
Could you please test the app with new installer and see if everything is
working fine?

I may not have chance to take a look until tomorrow morning.

Thanks

**Comment by sherebiahtishbi** [comment]
I did quick smoke test on my side and found everything okay with app post API changes. A peaceful note to go to bed with!!! 😊

**Comment by sermonindex-dev** [comment]
brothers I just verified the new API changes work well with the new installer also!

**Comment by sherebiahtishbi** [comment]
Excellent!! Thanks bro for verifying it.

**Comment by Llewellynvdm** [comment]
Brother @sermonindex-dev I just checked the API, and it has not been update:
![image](https://user-images.githubusercontent.com/5607939/81622910-86bb1e00-93f2-11ea-8cc8-87285035ba92.png)
As you can see the preacher_description is still showing, so is the change to access the speaker name. You will have to make a pull request on the server to update the API on https://api.sermonindex.net/

Let me know if you need help with that.

**Comment by sermonindex-dev** [comment]
If you have time to run the update that would be tremendous. I do not believe there are a huge amount of additions to the audio sermon section just maybe a few hundred.

**Comment by sherebiahtishbi** [comment]
Looks like API still does not reflect the changes @Llewellynvdm has made. I am still getting the same JSON which has same lengthy speaker description for each sermon of that speaker..see below for an example. Or probably it is the issue in the data itself where sermon description is by mistake filled out with preacher/speaker bio???

{

    "name": "A. Paget Wilkes",
    "image": "",
    "description": "",
    "sermons": [
        {
            "title": "Sanctification - Part 1 (reading)",
            "url": "http:\/\/api.sermonindex.net\/SID13470",
            "size": "0",
            "format": "mp3",
            "scripture": "",
            "topic": "Audio Books",
            "description": "Alpheus Paget Wilkes (19 January 1871 \u2013 5 October 1934) was an English evangelical Christian missionary to Japan who was one of the founders of the Japan Evangelistic Band in 1903. In addition to extensive mission work in Japan, and touring South East Asia, he wrote a number of penetrating expositions of Christian scriptures.",
            "download": "http:\/\/api.sermonindex.net\/SID13470-download",
            "preacher_name": "A. Paget Wilkes",
            "preacher_image": "",
            "preacher_description": "",
            "_scripture": []
        },
        {
            "title": "Sanctification - Part 2 (reading)",
            "url": "http:\/\/api.sermonindex.net\/SID13471",
            "size": "0",
            "format": "mp3",
            "scripture": "",
            "topic": "Audio Books",
            "description": "Alpheus Paget Wilkes (19 January 1871 \u2013 5 October 1934) was an English evangelical Christian missionary to Japan who was one of the founders of the Japan Evangelistic Band in 1903. In addition to extensive mission work in Japan, and touring South East Asia, he wrote a number of penetrating expositions of Christian scriptures.",
            "download": "http:\/\/api.sermonindex.net\/SID13471-download",
            "preacher_name": "A. Paget Wilkes",
            "preacher_image": "",
            "preacher_description": "",
            "_scripture": []
        },
        {
            "title": "Sanctification - Part 3 (reading)",
            "url": "http:\/\/api.sermonindex.net\/SID13472",
            "size": "0",
            "format": "mp3",
            "scripture": "",
            "topic": "Audio Books",
            "description": "Alpheus Paget Wilkes (19 January 1871 \u2013 5 October 1934) was an English evangelical Christian missionary to Japan who was one of the founders of the Japan Evangelistic Band in 1903. In addition to extensive mission work in Japan, and touring South East Asia, he wrote a number of penetrating expositions of Christian scriptures.",
            "download": "http:\/\/api.sermonindex.net\/SID13472-download",
            "preacher_name": "A. Paget Wilkes",
            "preacher_image": "",
            "preacher_description": "",
            "_scripture": []
        }
}

**Comment by Llewellynvdm** [comment]
Yes like I said, for those changes to take full effect a `git pull` must be done in the root folder of the API on the server. I did not backup that server access details, so brother Greg will have to do that, or send me a private message with the details, if I should do it. I setup the API via git last time, that is if I remember correctly, so a basic `git pull` should do the trick.

**Comment by sherebiahtishbi** [comment]
okay fine....lets wait for the new changes to be visible. I liked the new speaker.json structure! Fantastic!

**Comment by sermonindex-dev** [comment]
brother,

send me details on step by step simply how to do this pull and I can try
and get it done right away.


*Greg Gordon*

*"There are many of us that are willing to do great things for the Lord,
but few of us are willing to do little things." - D.L. Moody*

**Comment by Llewellynvdm** [comment]
Okay, [here is a quick tutorial](https://youtu.be/fE39_ECvb3g), let me know if this helps, and if you need more info.

**Comment by sermonindex-dev** [comment]
brother,  thank you the git pull should be accomplished now.
