### ISSUE TITLE
API with all sermons related to scripture

### ISSUE THREAD

**Issue by sherebiahtishbi** [sermonindex/audio_api#7]
@Llewellynvdm can we have this API available please? I see that I get all sermons for a speaker or a topic but not for a selected scripture. I am upgrading the app to list sermons by topic & scripture as well and the current scripture API will not suffice. Let me know if you want to understand what I am asking for...I can have video call with you on Google meet.

**Comment by Llewellynvdm** [comment]
Yes I first did the speakers, adding the changes you asked for. Would be great to have a quick chat about the way forward. See whatever changes we make, we should try and keep the existing API stable for any other silent devs who are already using it. As you may have experienced yourself in the past, when API's just change un-announced it is very discouraging for those who are already using it. So this far I have made changes that will allow for a much more standardization, and yet still allow other divers delivery models.

So we did the [speakers](https://github.com/sermonindex/audio_api/tree/master/speaker_sermons), and we did the same for the [topics](https://github.com/sermonindex/audio_api/tree/master/topic_sermons) only difference with the topics is that I did not setup a topics.json file like I did with the [speakers.json](https://github.com/sermonindex/audio_api/blob/master/speakers.json) I could add a file like that, very easy.

The scripture is a little more complex as it has var more variations then topics or speakers. So for this having a chat will be helpful.

When will work for you?

**Comment by sherebiahtishbi** [comment]
lets meet now brother.

**Comment by Llewellynvdm** [comment]
I am back in this room https://meet.google.com/xrn-bwno-nir

**Comment by Llewellynvdm** [comment]
I waited in the google meet-up room for 2 hours now, not sure why it did not work out, but we will have to reschedule for some time next week. Here is a link to setup a meeting with me https://vdm.bz/get-meeting-llewellyn

**Comment by sherebiahtishbi** [comment]
My sincere apologies brother. When Ijoined you werent there and when you
came in I had left!!! :) Lets meet next week.

**Comment by Llewellynvdm** [comment]
Seems resolved with https://github.com/sermonindex/audio_api/commit/80952e108647d7a15870d3e5e8a3473a8b80c404
