### ISSUE TITLE
api for pdf needs attention

### ISSUE THREAD

**Issue by sherebiahtishbi** [sermonindex/audio_api#9]
@Llewellynvdm I just noticed that download url for pdf coming in json doesn't work properly. See below example
`  {

            "title": "(Pdf Book) Behold I Will Do A New Thing",
            "url": "http:\/\/api.sermonindex.net\/SID26404.pdf",
            "size": "0",
            "format": "pdf",
            "scripture": "",
            "topic": "Ebooks",
            "description": "",
            "download": "http:\/\/api.sermonindex.net\/SID26404.pdf-download",
            "speaker_name": "Bakht Singh",
            "_scripture": []
        }
`

If I take that url from "download:" and paste it in the browser it just redirects me to github repository page. Can you look into it please?

**Comment by Llewellynvdm** [comment]
hmm, we do not have the PDF's but only audio. So I will remove the PDF's :+1:

**Comment by sherebiahtishbi** [comment]
On the site there are pdfs so not sure what you meant when you say we don't
have PDFs

**Comment by Llewellynvdm** [comment]
Yes the website does, even videos... :) but this API is only "[audio_api](https://github.com/sermonindex/audio_api)"

When ever you open any link and it opens [GitHub](https://github.com/sermonindex), that means the file does not exist.

**Comment by Llewellynvdm** [comment]
There are plans to extend the API to other areas, but this has not been done.

**Comment by sherebiahtishbi** [comment]
Okay, that's good to know. In that case is it possible to expose only those
speakers/sermons which are having audio format?

Currently json gives everything in the sermon listings, audio+PDFs. If we
can update apis to expose only audio sermons it will eliminate the
confusion.

Please let me know what you think.

Sherebiah

**Comment by Llewellynvdm** [comment]
Yes indeed that is what I said in my [second post on this thread](https://github.com/sermonindex/audio_api/issues/9#issuecomment-632823931) :)

> hmm, we do not have the PDF's but only audio. So I will remove the PDF's :+1:

**Comment by Llewellynvdm** [comment]
With that any speaker that does not have audio will also be removed, I will try to do this in the next few days.

**Comment by Llewellynvdm** [comment]
Seems resolved with https://github.com/sermonindex/audio_api/commit/9701f47235a46582fcc53b282f33109c8f07144e
